//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean teleport
        {
            get
            {
                return SteamVR_Actions.default_teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.default_pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton skeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_skeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton skeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_skeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Pose squeezeLeftHand
        {
            get
            {
                return SteamVR_Actions.default_squeezeLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Pose squeezeRightHand
        {
            get
            {
                return SteamVR_Actions.default_squeezeRightHand;
            }
        }
    }
}
